[package]
name = "pbrt"
version = "0.6.2"
authors = ["Jan Walter <jan@janwalter.com>"]
edition = "2018"

[features]
default = ["openexr"]

[dependencies]

atom = "0.3.5"
atomic = "0.4"
byteorder = "1"
crossbeam = "0.7"
getopts="0.2"
half="1"
hexf = "0.1.0"
image="*"
lazy_static = "1.3.0"
num="*"
num_cpus = "1.10"
openexr = { version = "0.6", optional = true }
pbr = "1.0"
pest = "2.1"
pest_derive = "2.1"
ply-rs = "0.1.2"
rayon = "1.1"
time = "0.1"
typed-arena = "1.4"
structopt = "0.2"
