[package]
authors = ["Jan Walter <jan@janwalter.com>"]
edition = "2018"
name = "pbrt"
version = "0.8.1"
[dependencies]
atom = "0.3.5"
atomic = "0.4.6"
byteorder = "1.3.4"
crossbeam = "0.7.3"
crossbeam-channel = "0.4.3"
hexf = "0.1.0"
image = "0.23.7"
lazy_static = "1.4.0"
num = "0.3.0"
num_cpus = "1.13.0"
pbr = "1.0.3"
pest = "2.1.3"
pest_derive = "2.1.0"
ply-rs = "0.1.2"
rayon = "1.3.1"
smallvec = "1.4.1"
structopt = "0.3.15"
strum = "0.18.0"
strum_macros = "0.18.0"
typed-arena = "2.0.1"

[[bin]]
name = "rs_pbrt"
path = "src/bin/rs_pbrt.rs"
