[package]
name = "pbrt"
version = "0.4.4"
authors = ["Jan Walter <jan@janwalter.com>"]

[features]
default = ["openexr"]

[dependencies]

atomic = "0.4"
byteorder = "1"
crossbeam = "0.5"
getopts="0.2.15"
half="1"
hexf = "0.1.0"
image="*"
num="*"
num_cpus = "1.2"
openexr = { version = "0.6", optional = true }
pbr = "1.0"
pest = "2.0"
pest_derive = "2.0"
ply-rs = "0.1.1"
rayon = "1.0"
# Force a more recent of skeptic to fix needless recompiles
skeptic = "0.13.4"
time = "0.1"
typed-arena = "1.3.0"
