[package]
name = "pbrt"
version = "0.4.1"
authors = ["Jan Walter <jan@janwalter.com>"]

[features]
default = ["openexr"]

[dependencies]

crossbeam = "0.4"
getopts="0.2.15"
half="1"
hexf = "0.1.0"
image="0.19"
num="*"
num_cpus = "1.2"
openexr = { version = "0.6", optional = true }
pbr = "1.0"
pest = "^1.0"
pest_derive = "^1.0"
ply-rs = "0.1.1"
rayon = "1.0"
time = "0.1"
typed-arena = "1.3.0"
atomic = "0.4"
