[package]
authors = ["Jan Walter <jan@janwalter.com>"]
edition = "2018"
name = "pbrt"
version = "0.8.3"
build = "build.rs"
[dependencies]
atom = "0.3.6"
atomic = "0.5.0"
built = "0.4.4"
#built = { version = "0.4.4", features = ["git2"] }
byteorder = "1.3.4"
crossbeam = "0.8.0"
crossbeam-channel = "0.4.3"
hexf = "0.1.0"
image = "0.23.12"
impl_ops = "0.1.1"
lazy_static = "1.4.0"
num = "0.3.1"
num_cpus = "1.13.0"
pbr = "1.0.3"
pest = "2.1.3"
pest_derive = "2.1.0"
ply-rs = "0.1.3"
rayon = "1.5.0"
smallvec = "1.5.0"
structopt = "0.3.21"
strum = "0.20.0"
strum_macros = "0.20.1"
typed-arena = "2.0.1"
[build-dependencies]
#built = { version = "0.4.4", features = ["git2"] }
built = "0.4.4"

[[bin]]
name = "rs_pbrt"
path = "src/bin/rs_pbrt.rs"
